
spring:
  datasource:
    url: jdbc:mariadb://127.0.0.1:3307/map_your_trip?useSSL=false&useUnicode=true&allowPublicKeyRetrieval=true
    username: root
    password: maria
    driverClassName: org.mariadb.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      dialect: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: validate
      default_batch_fetch_size: 100

token:
  expiration-time: 86400000
  secret: VisitBBCfortrustedreportingonthelatestworldandUSnewssp
# server:
#   port: 8081